# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SNOWFLAKE
version: "2024.01.16"
slug: snowflake
description: Snowflake is a system that allows people from all over the world to access censored websites and applications.
url: "https://github.com/L0rdShrek/HA-addons/tree/main/snowflake"
arch:
  - amd64
init: false
